name = "AdversarialGridworld"
uuid = "f8394dfe-2452-4386-a2b1-ee52e0ba54cf"
authors = ["Anthony Corso <anthonycorso92@gmail.com>"]
version = "0.1.0"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
GridInterpolations = "bb4c363b-b914-514b-8517-4eb369bc008a"
LocalApproximationValueIteration = "a40420fb-f401-52da-a663-f502e5b95060"
LocalFunctionApproximation = "db97f5ab-fc25-52dd-a8f9-02a257c35074"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPSimulators = "e0d0a172-29c6-5d4e-96d0-f262df5d01fd"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
